"""Step 9 — structural variant generation/evaluation artifact.

Step 9 may run a protein design lane (RFdiffusion / ProteinMPNN / ESM) and/or a
variant evaluation lane (AlphaMissense / DynaMut2 / ESM). The hard constraint:
the agent does NOT freely emit RFdiffusion `contigs_dsl`; that is generated by
a deterministic template/validator in services/structure_service.py.

`CompoundScreeningArtifact` and compound fields remain for legacy JSON/API
compatibility only. Active workflow v0.1 Step 9 lanes are `protein_design` and
`variant_evaluation`; ZINC/ChEMBL compound screening is not an active Step 9
tool path.
"""

from __future__ import annotations

from typing import Literal, Optional
from pydantic import BaseModel, Field

from .common import ToolCallRecord


class Step9AvailableField(BaseModel):
    """Compact, raw-safe readiness inputs projected for Step 9 hard gate.

    These are intentionally non-sensitive references (refs/hashes/flags), never
    raw sequence or raw molecular payload. Retained for legacy hard-gate
    audit/compatibility only — production Stage 1 / Stage 2 / runtime planning
    consume `Step9InputField` (below) from the centralized
    `step_09_input_projection` module instead.
    """

    candidate_id: str
    field_ref: str
    provider: Literal["step_05", "step_07", "step_08", "inferred"]
    field_type: str
    value_kind: str
    source_ref: Optional[str] = None
    status: Literal["available", "blocked", "not_applicable"] = "available"


class Step9InputField(BaseModel):
    """Deterministic, raw-safe Step 9 input field produced by the centralized
    `step_09_input_projection.project_step9_inputs` layer.

    This is the SINGLE field shape Stage 1, Stage 2, and the runtime planner
    consume. Only the projection layer understands raw Step 5 / Step 7 /
    Step 8 / query artifact shapes; `source_path` records the schema
    location the field was derived from (a dotted schema path, never a
    storage path), and `runtime_lookup` records how to resolve the field at
    real execution time without embedding the raw value here.

    `field_ref` is guaranteed globally unique within a single projection
    (`step_09_input_projection.project_step9_inputs`): when two or more raw
    upstream fields (e.g. the same UniProt accession surfaced by both a Step
    5 candidate identifier and a Step 7 identifier-only sequence ref, or the
    same PDB id shared by two candidates' Step 8 complex results) would
    otherwise collide on the same `field_ref`, the projection layer merges
    them into one canonical field. `source_step`/`candidate_id` then carry
    the first-seen source; `source_steps`/`candidate_ids` carry every
    contributing source so no provenance is lost.
    """

    field_ref: str
    candidate_id: Optional[str] = None
    candidate_ids: list[str] = Field(default_factory=list)
    source_step: Literal["step_05", "step_07", "step_08", "query"]
    source_steps: list[str] = Field(default_factory=list)
    source_artifact: str
    source_path: str
    field_name: str
    field_type: str
    value_kind: str
    semantic_role: Optional[str] = None
    chain_role: Optional[str] = None
    supports_tool_args: list[str] = Field(default_factory=list)
    can_resolve_at_runtime: bool = False
    llm_safe_metadata: dict = Field(default_factory=dict)
    runtime_lookup: dict = Field(default_factory=dict)
    status: Literal["available", "missing", "blocked", "not_applicable"] = "available"
    missing_reason: Optional[str] = None


class Step9HardGateAllowedTool(BaseModel):
    tool_name: str
    lane_type: Literal["protein_design", "variant_evaluation", "compound_screening"]
    candidate_id: str
    rationale: Optional[str] = None


class Step9HardGateBlockedTool(BaseModel):
    tool_name: str
    lane_type: Literal["protein_design", "variant_evaluation", "compound_screening"]
    candidate_id: str
    reason: str
    rationale: Optional[str] = None


class Step9ToolSchemaRequirement(BaseModel):
    candidate_id: str
    tool_name: str
    lane_type: Literal["protein_design", "variant_evaluation", "compound_screening"]
    required_fields: list[str] = Field(default_factory=list)
    schema_source: Literal["tooluniverse", "signature", "tooluniverse_or_signature", "unavailable"]
    satisfiable_required_fields: list[str] = Field(default_factory=list)
    missing_required_fields: list[str] = Field(default_factory=list)
    hard_gate_decision: Literal["allowed", "blocked"]
    reason: str


class Step9LaneStatus(BaseModel):
    lane_type: Literal["protein_design", "variant_evaluation", "compound_screening"]
    candidate_id: str
    candidate_type: str
    status: Literal["ready", "blocked", "not_applicable", "partial", "partial_or_skipped"]
    allowed_tools: list[str] = Field(default_factory=list)
    blocked_tools: list[str] = Field(default_factory=list)
    missing_requirements: list[str] = Field(default_factory=list)
    gate_reasons: list[str] = Field(default_factory=list)
    available_field_refs: list[str] = Field(default_factory=list)


class Step9ReadinessSummary(BaseModel):
    total_candidates: int = 0
    protein_design_candidates: int = 0
    protein_design_ready_candidates: int = 0
    protein_design_blocked_candidates: int = 0
    protein_design_not_applicable_candidates: int = 0
    variant_evaluation_candidates: int = 0
    variant_evaluation_ready_candidates: int = 0
    variant_evaluation_blocked_candidates: int = 0
    variant_evaluation_not_applicable_candidates: int = 0
    compound_candidates: int = 0
    compound_candidate_with_tools: int = 0
    hard_gate_allowed_tool_count: int = 0
    hard_gate_blocked_tool_count: int = 0


class Step9LaneReadinessProfile(BaseModel):
    status: Literal["ready", "blocked", "not_applicable"] = "not_applicable"
    ready_tool_count: int = 0
    blocked_tool_count: int = 0
    missing_requirements: list[str] = Field(default_factory=list)
    allowed_tools: list[str] = Field(default_factory=list)
    blocked_tools: list[str] = Field(default_factory=list)


class ProteinDesignVariant(BaseModel):
    variant_id: str
    parent_structure_input_id: str
    design_method: Literal["rfdiffusion", "proteinmpnn", "esm", "other"]
    contigs_dsl: Optional[str] = None  # deterministic template only
    output_artifact_id: Optional[str] = None
    stability_score: Optional[float] = None
    notes: Optional[str] = None


CompoundSourceLibrary = Literal[
    "ZINC",
    "ZINC15",
    "ZINC22",
    "Enamine",
    "SPECS",
    "ChEMBL",
    "PubChem",
    "DrugBank",
    "literature_mined",
    "client_provided",
    "other",
]

CompoundSourceRuntimeStatus = Literal[
    "success",
    "failed",
    "skipped",
    "dependency_unavailable",
    "not_run",
    "unknown",
]


class CompoundHit(BaseModel):
    """Legacy compound hit schema retained for backward-compatible artifacts."""

    compound_id: str
    source_library: CompoundSourceLibrary
    smiles: str
    similarity_score: Optional[float] = None
    source_database_version: Optional[Literal["ZINC15", "ZINC22", "unknown"]] = None
    source_tool_name: Optional[str] = None
    source_runtime_status: Optional[CompoundSourceRuntimeStatus] = None
    notes: Optional[str] = None


class ProteinDesignArtifact(BaseModel):
    run_id: str
    step_id: str = "step_09_structure_design"
    created_at: str
    design_status: Literal["ok", "partial", "skipped", "failed"] = "skipped"
    variants: list[ProteinDesignVariant] = Field(default_factory=list)
    tool_call_records: list[ToolCallRecord] = Field(default_factory=list)


class CompoundScreeningArtifact(BaseModel):
    """Legacy-compatible Step 9 artifact.

    The class name and compound fields are kept to avoid breaking existing
    storage/API consumers. Current Step 9 active lanes are protein design and
    variant evaluation, so compound fields should remain empty/not_applicable.
    """

    run_id: str
    step_id: str = "step_09_structure_design"
    created_at: str
    screening_status: Literal["ok", "partial", "skipped", "failed"] = "skipped"
    compound_hits: list[CompoundHit] = Field(default_factory=list)
    tool_call_records: list[ToolCallRecord] = Field(default_factory=list)
    step9_available_fields: list[Step9AvailableField] = Field(default_factory=list)
    step9_readiness_summary: Step9ReadinessSummary = Field(default_factory=Step9ReadinessSummary)
    step9_lane_statuses: list[Step9LaneStatus] = Field(default_factory=list)
    step9_hard_gate_allowed_tools: list[Step9HardGateAllowedTool] = Field(
        default_factory=list
    )
    step9_hard_gate_blocked_tools_with_reason: list[Step9HardGateBlockedTool] = Field(
        default_factory=list
    )
    step9_tool_schema_requirements: list[Step9ToolSchemaRequirement] = Field(
        default_factory=list
    )
    step9_stage1_catalog_tool_names: list[str] = Field(default_factory=list)
    step9_stage1_selected_tools: list[dict] = Field(default_factory=list)
    step9_stage1_rejected_tools_with_reason: list[dict] = Field(default_factory=list)
    step9_stage1_selection_source: str = "not_run"
    step9_stage1_prompt_cache_layout_version: str = "not_run"
    step9_stage2_schema_survivors: list[str] = Field(default_factory=list)
    step9_stage2_mapped_tools: list[dict] = Field(default_factory=list)
    step9_stage2_uninvokable_tools: list[str] = Field(default_factory=list)
    step9_stage2_uninvokable_tool_details: list[dict] = Field(default_factory=list)
    step9_stage2_argument_mapping_audit: list[dict] = Field(default_factory=list)
    step9_stage2_prompt_cache_layout_version: str = "not_run"
    step9_runtime_execution_plan: list[dict] = Field(default_factory=list)
    step9_runtime_resolved_tools: list[dict] = Field(default_factory=list)
    step9_runtime_unresolved_tools: list[dict] = Field(default_factory=list)
    step9_runtime_resolver_audit: list[dict] = Field(default_factory=list)
    step9_runtime_kwargs_contracts: list[dict] = Field(default_factory=list)
    step9_runtime_kwargs_contract_audit: list[dict] = Field(default_factory=list)
    step9_runtime_execution_mode: str = "not_run"
    step9_missing_inputs: list[str] = Field(default_factory=list)
    # ── Step9InputProjection (centralized deterministic projection layer) ──
    # Production Stage 1 / Stage 2 / runtime planning consume ONLY these
    # fields; the legacy `step9_hard_gate_*` / `step9_available_fields`
    # fields above stay for backward-compatible audit and no longer drive
    # catalog/selection/mapping/planning.
    step9_input_fields: list[Step9InputField] = Field(default_factory=list)
    step9_input_projection_summary: dict = Field(default_factory=dict)
    step9_projection_missing_inputs: list[str] = Field(default_factory=list)
    # ── Step 9 real MCP execution (Turn C) ──────────────────────────────────
    # Populated once the runtime resolver (`step_09_runtime_execution`)
    # resolves a Stage 2 kwargs contract to real values and
    # `StructureAndDesignAgent.run_step_9` actually invokes the tool via
    # `mcp_client.call_tool`. `tool_call_records` (above) carries the
    # canonical per-call record (with `tool_output_ref` into
    # `tool_outputs/step_09/`); these two fields are a compact, redundant
    # index over the same calls for convenient Step 9 auditing.
    step9_runtime_executed_tools: list[str] = Field(default_factory=list)
    step9_runtime_execution_records: list[dict] = Field(default_factory=list)
    protein_design_readiness: Step9LaneReadinessProfile = Field(
        default_factory=Step9LaneReadinessProfile
    )
    variant_evaluation_readiness: Step9LaneReadinessProfile = Field(
        default_factory=Step9LaneReadinessProfile
    )
    compound_screening_readiness: Step9LaneReadinessProfile = Field(
        default_factory=Step9LaneReadinessProfile
    )
