"""Step 9 — protein_design_artifact + compound_screening_artifact.

Step 9 may run a protein design lane (RFdiffusion / ProteinMPNN / ESM) and/or a
compound screening lane (ChEMBL / ZINC libraries). The hard constraint: the
agent does NOT freely emit RFdiffusion `contigs_dsl`; that is generated by a
deterministic template/validator in services/structure_service.py.
"""

from __future__ import annotations

from typing import Literal, Optional
from pydantic import BaseModel, Field

from .common import ToolCallRecord


class ProteinDesignVariant(BaseModel):
    variant_id: str
    parent_structure_input_id: str
    design_method: Literal["rfdiffusion", "proteinmpnn", "esm", "other"]
    contigs_dsl: Optional[str] = None  # deterministic template only
    output_artifact_id: Optional[str] = None
    stability_score: Optional[float] = None
    notes: Optional[str] = None


CompoundSourceLibrary = Literal[
    "ZINC",
    "ZINC15",
    "ZINC22",
    "Enamine",
    "SPECS",
    "ChEMBL",
    "PubChem",
    "DrugBank",
    "literature_mined",
    "client_provided",
    "other",
]

CompoundSourceRuntimeStatus = Literal[
    "success",
    "failed",
    "skipped",
    "dependency_unavailable",
    "not_run",
    "unknown",
]


class CompoundHit(BaseModel):
    """Per IO Schema §Step 9 compound_library_screening_lane.standardized_compound_records[].

    Important: current ToolUniverse `ZINC_*` wrappers must NOT be labeled
    `ZINC22` unless the upstream source is explicitly confirmed. Default to
    `ZINC` (family) or `ZINC15` when the endpoint is known, and leave
    `source_database_version` as `unknown` otherwise.
    """

    compound_id: str
    source_library: CompoundSourceLibrary
    smiles: str
    similarity_score: Optional[float] = None
    source_database_version: Optional[Literal["ZINC15", "ZINC22", "unknown"]] = None
    source_tool_name: Optional[str] = None
    source_runtime_status: Optional[CompoundSourceRuntimeStatus] = None
    notes: Optional[str] = None


class ProteinDesignArtifact(BaseModel):
    run_id: str
    step_id: str = "step_09_structure_design"
    created_at: str
    design_status: Literal["ok", "partial", "skipped", "failed"] = "skipped"
    variants: list[ProteinDesignVariant] = Field(default_factory=list)
    tool_call_records: list[ToolCallRecord] = Field(default_factory=list)


class CompoundScreeningArtifact(BaseModel):
    run_id: str
    step_id: str = "step_09_structure_design"
    created_at: str
    screening_status: Literal["ok", "partial", "skipped", "failed"] = "skipped"
    compound_hits: list[CompoundHit] = Field(default_factory=list)
    tool_call_records: list[ToolCallRecord] = Field(default_factory=list)
