"""Step 9 — protein_design_artifact + variant_evaluation + compound_screening_artifact.

Step 9 may run a protein design lane (RFdiffusion / ProteinMPNN / ESM) and/or a
compound screening lane (ChEMBL / ZINC libraries). The hard constraint: the
agent does NOT freely emit RFdiffusion `contigs_dsl`; that is generated by a
deterministic template/validator in services/structure_service.py.
"""

from __future__ import annotations

from typing import Literal, Optional
from pydantic import BaseModel, Field

from .common import ToolCallRecord


class Step9AvailableField(BaseModel):
    """Compact, raw-safe readiness inputs projected for Step 9 hard gate.

    These are intentionally non-sensitive references (refs/hashes/flags), never
    raw sequence or raw molecular payload.
    """

    candidate_id: str
    field_ref: str
    provider: Literal["step_05", "step_07", "step_08", "inferred"]
    field_type: str
    value_kind: str
    source_ref: Optional[str] = None
    status: Literal["available", "blocked", "not_applicable"] = "available"


class Step9HardGateAllowedTool(BaseModel):
    tool_name: str
    lane_type: Literal["protein_design", "variant_evaluation", "compound_screening"]
    candidate_id: str
    rationale: Optional[str] = None


class Step9HardGateBlockedTool(BaseModel):
    tool_name: str
    lane_type: Literal["protein_design", "variant_evaluation", "compound_screening"]
    candidate_id: str
    reason: str
    rationale: Optional[str] = None


class Step9ToolSchemaRequirement(BaseModel):
    candidate_id: str
    tool_name: str
    lane_type: Literal["protein_design", "variant_evaluation", "compound_screening"]
    required_fields: list[str] = Field(default_factory=list)
    schema_source: Literal["tooluniverse", "signature", "tooluniverse_or_signature", "unavailable"]
    satisfiable_required_fields: list[str] = Field(default_factory=list)
    missing_required_fields: list[str] = Field(default_factory=list)
    hard_gate_decision: Literal["allowed", "blocked"]
    reason: str


class Step9LaneStatus(BaseModel):
    lane_type: Literal["protein_design", "variant_evaluation", "compound_screening"]
    candidate_id: str
    candidate_type: str
    status: Literal["ready", "blocked", "not_applicable", "partial", "partial_or_skipped"]
    allowed_tools: list[str] = Field(default_factory=list)
    blocked_tools: list[str] = Field(default_factory=list)
    missing_requirements: list[str] = Field(default_factory=list)
    gate_reasons: list[str] = Field(default_factory=list)
    available_field_refs: list[str] = Field(default_factory=list)


class Step9ReadinessSummary(BaseModel):
    total_candidates: int = 0
    protein_design_candidates: int = 0
    protein_design_ready_candidates: int = 0
    protein_design_blocked_candidates: int = 0
    protein_design_not_applicable_candidates: int = 0
    variant_evaluation_candidates: int = 0
    variant_evaluation_ready_candidates: int = 0
    variant_evaluation_blocked_candidates: int = 0
    variant_evaluation_not_applicable_candidates: int = 0
    compound_candidates: int = 0
    compound_candidate_with_tools: int = 0
    hard_gate_allowed_tool_count: int = 0
    hard_gate_blocked_tool_count: int = 0


class Step9LaneReadinessProfile(BaseModel):
    status: Literal["ready", "blocked", "not_applicable"] = "not_applicable"
    ready_tool_count: int = 0
    blocked_tool_count: int = 0
    missing_requirements: list[str] = Field(default_factory=list)
    allowed_tools: list[str] = Field(default_factory=list)
    blocked_tools: list[str] = Field(default_factory=list)


class ProteinDesignVariant(BaseModel):
    variant_id: str
    parent_structure_input_id: str
    design_method: Literal["rfdiffusion", "proteinmpnn", "esm", "other"]
    contigs_dsl: Optional[str] = None  # deterministic template only
    output_artifact_id: Optional[str] = None
    stability_score: Optional[float] = None
    notes: Optional[str] = None


CompoundSourceLibrary = Literal[
    "ZINC",
    "ZINC15",
    "ZINC22",
    "Enamine",
    "SPECS",
    "ChEMBL",
    "PubChem",
    "DrugBank",
    "literature_mined",
    "client_provided",
    "other",
]

CompoundSourceRuntimeStatus = Literal[
    "success",
    "failed",
    "skipped",
    "dependency_unavailable",
    "not_run",
    "unknown",
]


class CompoundHit(BaseModel):
    """Per IO Schema §Step 9 compound_library_screening_lane.standardized_compound_records[].

    Important: current ToolUniverse `ZINC_*` wrappers must NOT be labeled
    `ZINC22` unless the upstream source is explicitly confirmed. Default to
    `ZINC` (family) or `ZINC15` when the endpoint is known, and leave
    `source_database_version` as `unknown` otherwise.
    """

    compound_id: str
    source_library: CompoundSourceLibrary
    smiles: str
    similarity_score: Optional[float] = None
    source_database_version: Optional[Literal["ZINC15", "ZINC22", "unknown"]] = None
    source_tool_name: Optional[str] = None
    source_runtime_status: Optional[CompoundSourceRuntimeStatus] = None
    notes: Optional[str] = None


class ProteinDesignArtifact(BaseModel):
    run_id: str
    step_id: str = "step_09_structure_design"
    created_at: str
    design_status: Literal["ok", "partial", "skipped", "failed"] = "skipped"
    variants: list[ProteinDesignVariant] = Field(default_factory=list)
    tool_call_records: list[ToolCallRecord] = Field(default_factory=list)


class CompoundScreeningArtifact(BaseModel):
    run_id: str
    step_id: str = "step_09_structure_design"
    created_at: str
    screening_status: Literal["ok", "partial", "skipped", "failed"] = "skipped"
    compound_hits: list[CompoundHit] = Field(default_factory=list)
    tool_call_records: list[ToolCallRecord] = Field(default_factory=list)
    step9_available_fields: list[Step9AvailableField] = Field(default_factory=list)
    step9_readiness_summary: Step9ReadinessSummary = Field(default_factory=Step9ReadinessSummary)
    step9_lane_statuses: list[Step9LaneStatus] = Field(default_factory=list)
    step9_hard_gate_allowed_tools: list[Step9HardGateAllowedTool] = Field(
        default_factory=list
    )
    step9_hard_gate_blocked_tools_with_reason: list[Step9HardGateBlockedTool] = Field(
        default_factory=list
    )
    step9_tool_schema_requirements: list[Step9ToolSchemaRequirement] = Field(
        default_factory=list
    )
    step9_stage1_catalog_tool_names: list[str] = Field(default_factory=list)
    step9_stage1_selected_tools: list[dict] = Field(default_factory=list)
    step9_stage1_rejected_tools_with_reason: list[dict] = Field(default_factory=list)
    step9_stage1_selection_source: str = "not_run"
    step9_stage1_prompt_cache_layout_version: str = "not_run"
    step9_missing_inputs: list[str] = Field(default_factory=list)
    protein_design_readiness: Step9LaneReadinessProfile = Field(
        default_factory=Step9LaneReadinessProfile
    )
    variant_evaluation_readiness: Step9LaneReadinessProfile = Field(
        default_factory=Step9LaneReadinessProfile
    )
    compound_screening_readiness: Step9LaneReadinessProfile = Field(
        default_factory=Step9LaneReadinessProfile
    )
